version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
    ports:
      - "10000:8080"
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - dev-miniflux-db:/var/lib/postgresql/data
  fluentd:
    image: fluent/fluentd:v1.3-debian
    volumes:
      - dev-fluentd-db:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
volumes:
  dev-miniflux-db:
  dev-fluentd-db:
